### PR TITLE
library: Port HTTP Image, Color Dialog demos to Vala

### PR DESCRIPTION
**Pull request by Diego-Ivan**
Ports HTTP Image and Color Dialog demos to Vala

### CODE REVIEW

**Review by lw64 — CHANGES_REQUESTED** [review]
Looks very good. After fixing these small issues it can be merged!

**Comment by Diego-Ivan** [comment]
Thanks for the review, they're now fixed @lw64 :smile:

**Review by lw64 — APPROVED** [review]

**Comment by sonnyp** [comment]
@lw64 feel free to "Squash and merge" after reviewing

**Comment by sonnyp** [comment]
@Diego-Ivan thanks a lot

Please feel free to add yourself to the list of contributors in `about.js` in your next PR :pray:

**Pull request merged**
