### PR TITLE
Rename workbench-api.vala to workbench.vala

### PR DESCRIPTION
**Pull request by Hofer-Julian**
This original rename in vala.js made it harder to see how the pieces are connected

### CODE REVIEW

**Review by andyholmes — APPROVED** [review]

**Comment by andyholmes** [comment]
LGTM, I'll just cc @lw64 in case there's something I don't know.

**Comment by lw64** [comment]
I think you also need to adjust the `#!/usr/bin/env ...` in all demos.

**Comment by Hofer-Julian** [comment]
> I think you also need to adjust the `#!/usr/bin/env ...` in all demos.

I don't thinl so. They already all expect `workbench.vala`.

**Comment by lw64** [comment]
I see, alright then.

**Review by lw64 — APPROVED** [review]

**Pull request merged**
