### PR TITLE
library: Add vala demo for Preferences Window

### PR DESCRIPTION
**Pull request by SpikedPaladin**
Adds Vala code demo for Preferences Window

### CODE REVIEW

**Comment by sonnyp** [comment]
@SpikedPaladin would you like to add yourself to contributors in `about.js` ?

**Comment by SpikedPaladin** [comment]
@sonnyp should I make PR for that?

**Comment by sonnyp** [comment]
You can do it in this one

**Review by lw64 — CHANGES_REQUESTED** [review]
Looks good overall.

**Comment by SpikedPaladin** [comment]
@lw64 done

**Pull request merged**
