### PR TITLE
library: Add vala demo for Text Fields

### PR DESCRIPTION
**Pull request by SpikedPaladin**
Adds Vala code demo for Text Fields

### CODE REVIEW

**Comment by SpikedPaladin** [comment]
@lw64 done

**Review by lw64 — APPROVED** [review]

**Comment by sonnyp** [comment]
@SpikedPaladin thanks! 

Would you like to add your name to the `contributors` section of `about.js` ?
More ports to Vala are very welcome, we've been discussing how we can speed up the review process and automatically format code.

**Comment by SpikedPaladin** [comment]
@sonnyp yes, also I wanna add more vala ports later

**Comment by lw64** [comment]
Very cool. I will also try to review them without much delay!

**Pull request merged**
