### PR TITLE
Library: ported `Checkbox` in Rust

### PR DESCRIPTION
**Pull request by itsAdee**
Recently Learned about the availability of Rust in the Workbench.
I have added the checkbox implementation in Rust . It works on fine on the builder on my machine. Please Check it.

### CODE REVIEW

**Review by Hofer-Julian — COMMENTED** [review]
Looks good to me, but let's create closures instead of dedicated functions (similar to the javascript version)

**Comment by itsAdee** [comment]
> Looks good to me, but let's create closures instead of dedicated functions (similar to the javascript version)

Modified the code, please check this version of the code, and let me know of any anomaly.Thanks.

**Review by Hofer-Julian — APPROVED** [review]
The code looks good to me.
Will merge it when I checked it locally at home.
If another maintainer has time earlier, they can do it too and merge it then.

**Review by Hofer-Julian — APPROVED** [review]
Thank you!

**Pull request merged**
