### PR TITLE
library: Add HTTP Server entry

### LINKED ISSUE #19: HTTP Server demo
`SoupServer` can be used to make an HTTP server

Would be nice if the demo started a server and had a button to open the url in the browser to display whatever the server is serving.

There is an example here  https://gitlab.gnome.org/GNOME/gjs/-/blob/master/examples/

```
gjs -m http-server.js // start the server
```

the open `http://localhost:1080` in your browser

### LINKED ISSUE #414: HTTP Server demo
`SoupServer` can be used to make an HTTP server

Would be nice if the demo

Started a server and had a button to open the url in the browser to display whatever the server is serving.

There is an example here  https://gitlab.gnome.org/GNOME/gjs/-/blob/master/examples/

```
gjs -m http-server.js // start the server
```

the open `http://localhost:1080` in your browser

### PR DESCRIPTION
**Pull request by AkshayWarrier**
Closes workbenchdev/demos#19
I have directly copied the example from https://gitlab.gnome.org/GNOME/gjs/-/blob/master/examples/. The example only occasionally seems to work, and refuses to connect sometimes.

### CODE REVIEW

**Review by sonnyp — COMMENTED** [review]
https://github.com/sonnyp/Workbench/pull/444#issuecomment-1658745741

**Comment by AkshayWarrier** [comment]
Done https://gitlab.gnome.org/GNOME/gjs/-/issues/569

**Comment by sonnyp** [comment]
We could try in Vala and see if the same thing happen.

**Comment by sonnyp** [comment]
@AkshayWarrier wdyt trying in Vala?

**Comment by AkshayWarrier** [comment]
Yes I can try

**Comment by AkshayWarrier** [comment]
Yeah sure

**Pull request closed without merging**
